# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? ffc-sfd-crm
  : build:
      target: development
    image: ffc-sfd-crm-development
    container_name: ffc-sfd-crm-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      
