- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: CRM_TOPIC_ADDRESS
  value: "fcp-sfd-crm-events"
- key: CRM_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-crm"