- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: CRM_TOPIC_ADDRESS
  value: "fcp-sfd-crm-messages"
- key: CRM_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-crm"
- key: CRM_CLIENT_APP_ID
  value: "{{servicename}}-CLIENT-APP-ID"
- key: CRM_CLIENT_SECRET_VALUE
  value: "{{servicename}}-CLIENT-SECRET-VALUE"
  type: "keyvault"
- key: CRM_CLIENT_SECRET_ID
  value: "{{servicename}}-CLIENT-SECRET-ID"